---
repos:
  - repo: local
    hooks:
      - id: lint-markdown
        name: Lint Markdown files
        entry: npx --yes markdownlint-cli2
        language: system
        files: \.md$
        pass_filenames: true
      - id: lint-yaml
        name: Lint YAML files
        entry: yamllint
        language: conda
        files: \.(yaml|yml)$
        pass_filenames: true
