---
repos:
  - repo: local
    hooks:
      - id: lint-markdown
        name: Lint Markdown files
        entry: markdownlint-cli2
        language: node
        files: \.md$
        pass_filenames: true
        additional_dependencies: [markdownlint-cli2]
