---
repos:
  - repo: local
    hooks:
      - id: lint-markdown
        name: Lint Markdown files
        entry: markdownlint-cli2
        language: node
        files: \.md$
        pass_filenames: true
        additional_dependencies: [markdownlint-cli2]
      - id: lint-yaml
        name: Lint YAML files
        entry: yamllint
        language: conda
        files: \.(yaml|yml)$
        pass_filenames: true
        additional_dependencies: [yamllint]
